---
title: "Untitled"
author: "Daniel Pagotto"
date: "01/06/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

setwd("~/GitHub/dimensionamento/Agravos do SINAN/Animais peçonhentos")

```


```{r cars, message=FALSE, warning=FALSE}

animais <- read.dbc::read.dbc("ANIMBR21.dbc")

animais %>%  
  mutate(faixa_etaria = case_when(NU_IDADE_N < 4000 ~ "Menor que 1 ano",
                                  NU_IDADE_N > 4000 & NU_IDADE_N < 4005 ~ "Entre 1 e 4 anos",
                                  ))

#writexl::write_xlsx(animais_red, "animais.xlsx")

DT::datatable(animais_red)

```
# **Análise de incidentes por município**

### Tipo de animal 

```{r}
qtd_serpente <- 
  animais %>% 
  filter(ANI_SERPEN != "NA") %>% 
  group_by(ID_MN_RESI, faixa_etaria, DT_NOTIFIC) 
  
  
```


### Por classificação 

```{r}
qtd_serpente_classificacao <- 
  animais %>% 
  filter(ANI_SERPEN != "NA") %>% 
  group_by(ID_MN_RESI, SG_UF, TRA_CLASSI, DT_NOTIFIC) %>% 
  summarise(total = n())
  

a <- qtd_serpente_classificacao %>% 
  filter(SG_UF == "52") %>% 
  ggplot(aes(x = DT_NOTIFIC, y = total, col = TRA_CLASSI)) + geom_line() +
  scale_y_continuous(breaks = seq(1, 10, 2)) + theme_minimal()


plotly::ggplotly(a)


```





**negrito**
*itálico*

# Título 
## Subtítulo
### isso vai diminuindo

## Including Plots

Vamos escrever algo aqui para testar

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
