---
title: "Untitled"
author: "Daniel Pagotto"
date: "01/06/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

setwd("D:/Adaleny/Rstudio/animais peconhentos")

```


```{r cars, message=FALSE, warning=FALSE}

install.packages("read.dbc")
install.packages("lubridate")
library(tidyverse)
library(lubridate)

animais <- read.dbc::read.dbc("ANIMBR21.dbc")

base_animais <-animais %>%  
mutate(faixa_etaria = case_when(NU_IDADE_N < 4000 ~ "Menor que 1 ano",
                                NU_IDADE_N >= 4000 & NU_IDADE_N < 4005 ~ "Entre 1 e 4 anos",                                   NU_IDADE_N >= 4005 & NU_IDADE_N < 4015 ~ "Entre 5 e 14 anos",                                   NU_IDADE_N >= 4015 & NU_IDADE_N < 4025 ~ "Entre 15 e 24 anos", 
                                NU_IDADE_N >= 4025 & NU_IDADE_N < 4035 ~ "Entre 25 e 34 anos", 
                                NU_IDADE_N >= 4035 & NU_IDADE_N < 4045 ~ "Entre 35 e 44 anos", 
                                NU_IDADE_N >= 4045 & NU_IDADE_N < 4055 ~ "Entre 45 e 54 anos", 
                                NU_IDADE_N >= 4055 & NU_IDADE_N < 4065 ~ "Entre 55 e 64 anos", 
                                NU_IDADE_N >= 4065 ~ "65 ou mais "))%>%
mutate(tipo_animais = case_when(TP_ACIDENT == 1 ~ "Serpente",
                                TP_ACIDENT == 2 ~ "Aranha", 
                                TP_ACIDENT == 3 ~ "Escorpião",
                                TP_ACIDENT == 4 ~ "Lagarta", 
                                TP_ACIDENT == 5 ~ "Abelha", 
                                TP_ACIDENT == 6 ~ "Outros",
                                TP_ACIDENT == 9 ~ " Ignorado" ))%>%
mutate(gravidade = case_when(TRA_CLASSI == 1 ~ "Leve", 
                             TRA_CLASSI == 2 ~ "Moderado", 
                             TRA_CLASSI == 3 ~ "Grave", 
                             TRA_CLASSI == 9 ~ "Ignorado"))





glimpse(base_animais)

#writexl::write_xlsx(animais_red, "animais.xlsx")

DT::datatable(animais_red)

```
# **Análise de incidentes por município**

### Tipo de animal 

```{r}


qtd_serpente <- 
  base_animais %>% 
  filter(tipo_animais == "Serpente") %>% 
  group_by(tipo_animais,ID_MN_RESI, faixa_etaria, DT_NOTIFIC)%>%
  count(faixa_etaria)

 qtd_aranha <- 
  base_animais %>% 
  filter(tipo_animais == "Aranha") %>% 
  group_by(tipo_animais,ID_MN_RESI, faixa_etaria, DT_NOTIFIC)%>%
  count(faixa_etaria)
 
 qtd_escorpiao <- 
  base_animais %>% 
  filter(tipo_animais == "Escorpião") %>% 
  group_by(tipo_animais, ID_MN_RESI, faixa_etaria, DT_NOTIFIC)%>%
  count(faixa_etaria)
 
 qtd_lagarta <- 
  base_animais %>% 
  filter(tipo_animais== "Lagarta") %>% 
  group_by(tipo_animais, ID_MN_RESI, faixa_etaria, DT_NOTIFIC)%>%
  count(faixa_etaria)
 
  qtd_abelha <- 
  base_animais %>% 
  filter(tipo_animais == "Abelha") %>% 
  group_by(tipo_animais,ID_MN_RESI, faixa_etaria, DT_NOTIFIC)%>%
  count(faixa_etaria)

  Base_tipo_animal <- rbind(qtd_serpente,qtd_aranha,qtd_escorpiao,qtd_lagarta,qtd_abelha)
  
  
```


### Por classificação 

```{r}
qtd_serpente_classificacao <- 
  base_animais%>% 
  filter(tipo_animais == "Serpente") %>%
  group_by(tipo_animais, ID_MN_RESI, SG_UF, gravidade, DT_NOTIFIC) %>%
  summarise(total = n())%>%
  ungroup()
  
  
qtd_aranha_classificacao <- 
  base_animais%>% 
  filter(tipo_animais == "Aranha") %>% 
  group_by(tipo_animais,ID_MN_RESI, SG_UF, gravidade, DT_NOTIFIC) %>%
  summarise(total = n())%>%
  ungroup()
  


qtd_escorpiao_classificacao <- 
  base_animais%>% 
  filter(tipo_animais == "Escorpião") %>% 
  group_by(tipo_animais,ID_MN_RESI, SG_UF, gravidade, DT_NOTIFIC) %>%
  summarise(total = n())%>%
  ungroup()
  

qtd_lagarta_classificacao <- 
  base_animais%>% 
  filter(tipo_animais == "Lagarta") %>% 
  group_by(tipo_animais,ID_MN_RESI, SG_UF, gravidade, DT_NOTIFIC) %>% 
  summarise(total = n())%>%
  ungroup()
  
  
qtd_abelha_classificacao <- 
  base_animais%>% 
  filter(tipo_animais == "Abelha") %>% 
  group_by(tipo_animais, ID_MN_RESI, SG_UF, gravidade, DT_NOTIFIC) %>%
  summarise(total = n())%>%
  ungroup()
  

Base_classif <- rbind(qtd_serpente_classificacao,qtd_aranha_classificacao,qtd_escorpiao_classificacao,qtd_lagarta_classificacao,qtd_abelha_classificacao)


Base_classif$DT_NOTIFIC <- format(Base_classif$DT_NOTIFIC, "%m-%Y")



glimpse(Base_classif)

a <- Base_classif %>%
   filter(SG_UF == "52") %>% 
  ggplot(aes(x = DT_NOTIFIC , y = total, col = tipo_animais))+ geom_line() +
  scale_y_continuous(breaks = seq(1, 10, 2)) + theme_minimal()





plotly::ggplotly(a) 


```




## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
